id: P007893
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1987
  title: རྒྱུད་སྡེ་སྤྱིའི་རྣམ་གཞག་མཁས་པའི་ཡིད་འཕྲོག་
  author: ''
  volumes:
    86b16173939d46c6b0b3ac89bab3df80:
      image_group_id: I1CZ2015
      title: ''
      volume_number: 1
      total_pages: 60
ebook_metadata:
  title: རྒྱུད་སྡེ་སྤྱིའི་རྣམ་གཞག་མཁས་པའི་ཡིད་འཕྲོག་
  author: ''
  sku: P007893
  cover: cover.jpg
  layers:
  - pagination
