id: I85EBDF8F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T08:58:46+00:00'
last_modified: '2022-06-09T07:09:39.261702+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1987
  title: རྒྱུད་སྡེ་སྤྱིའི་རྣམ་གཞག་མཁས་པའི་ཡིད་འཕྲོག་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    72FE:
      image_group_id: I1CZ2015
      title: Volume 1 of rgyud sde spyi'i rnam gzhag mkhas pa'i yid 'phrog
      total_pages: 60
      order: 1
      base_file: 72FE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
